[colors.bright]
black = "#5c6a72"
blue = "#3a94c5"
cyan = "#35a77c"
green = "#8da101"
magenta = "#df69ba"
red = "#f85552"
white = "#e0dcc7"
yellow = "#dfa000"

[colors.normal]
black = "#5c6a72"
blue = "#3a94c5"
cyan = "#35a77c"
green = "#8da101"
magenta = "#df69ba"
red = "#f85552"
white = "#e0dcc7"
yellow = "#dfa000"

[colors.primary]
background = "#fdf6e3"
foreground = "#5c6a72"

[font]
 size =  9   # xmonad (external)
#size = 10   # unity  (external)
#size = 13   # unity  (built-in)

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.offset]
y = 0

[window]
 opacity = 0.85  # xmonad
#opacity = 1.0   # unity

[window.dimensions]
columns = 120
lines = 36

[window.padding]
x = 5
y = 5
