[aws]
disabled = true

[character]
success_symbol = '[❯❯❯](bold green)'
error_symbol = '[❯❯❯](bold red)'

[cmake]
disabled = true

[cmd_duration]
format = '[\($duration\)]($style) '
style = 'italic'

[directory]
style = 'bold'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = ''
style = 'italic'
ignore_branches = ['master', 'main']

[git_status]
conflicted = '!'
ahead = '>'
behind = '<'
diverged = '<>'
untracked = '%'
modified = '*'
style = 'bold'

[python]
format = '[${symbol}${pyenv_prefix}\(($virtualenv @ )(${version})\) ]($style)'
version_format = '${raw}'
symbol = ''
style = 'bold blue'
detect_extensions = []
